# Generated by Django 4.2 on 2023-12-30 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('Picture', models.ImageField(upload_to='uploads/profile_images', verbose_name='Picture')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'Profile',
            },
        ),
    ]
